
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: os3-manager-manager-role
rules:
- resources:
  - configmap
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - configmap/finalizers
  verbs:
  - update
- resources:
  - configmap/status
  verbs:
  - get
  - patch
  - update
- resources:
  - secret
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - secret/finalizers
  verbs:
  - update
- resources:
  - secret/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.baloise.ch
  resources:
  - copyresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.baloise.ch
  resources:
  - copyresources/finalizers
  verbs:
  - update
- apiGroups:
  - resource.baloise.ch
  resources:
  - copyresources/status
  verbs:
  - get
  - patch
  - update
