
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - resource.baloise.ch.baloise.ch
  resources:
  - copyresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.baloise.ch.baloise.ch
  resources:
  - copyresources/status
  verbs:
  - get
  - patch
  - update
