
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: os3-manager-manager-role
rules:
- resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - configmaps/finalizers
  verbs:
  - update
- resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - secrets/finalizers
  verbs:
  - update
- resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.baloise.ch
  resources:
  - copyresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.baloise.ch
  resources:
  - copyresources/finalizers
  verbs:
  - update
- apiGroups:
  - resource.baloise.ch
  resources:
  - copyresources/status
  verbs:
  - get
  - patch
  - update
